
import JSZip from 'jszip';
import saveAs from 'file-saver';
import { ExportFormat } from '../types';

// --- SHARED TEMPLATES ---
const readme = `# AI Generated Project

This project was generated by the AI Webpage Generator.

## To get started:

1.  Unzip the folder.
2.  Open your terminal and navigate to the project directory.
3.  Run \`npm install\` to install the dependencies.
4.  Run \`npm run dev\` to start the development server.
`;

const getBaseIndexHtml = (title: string, scriptSrc: string) => `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Inter', sans-serif;
      }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="${scriptSrc}"></script>
  </body>
</html>
`;

// --- HTML EXPORT ---
const getHtmlContent = (code: string, title: string) => `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Inter', sans-serif;
      }
    </style>
</head>
<body>
${code}
</body>
</html>
`;

// --- REACT PROJECT TEMPLATES ---
const reactPackageJson = `{
  "name": "react-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": { "dev": "vite", "build": "tsc && vite build", "preview": "vite preview" },
  "dependencies": { "react": "^18.2.0", "react-dom": "^18.2.0" },
  "devDependencies": {
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "@vitejs/plugin-react": "^4.2.1",
    "typescript": "^5.2.2",
    "vite": "^5.0.8"
  }
}`;
const reactViteConfig = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
export default defineConfig({ plugins: [react()] });`;
const reactTsConfig = `{
  "compilerOptions": {
    "target": "ES2020", "useDefineForClassFields": true, "lib": ["ES2020", "DOM", "DOM.Iterable"], "module": "ESNext",
    "skipLibCheck": true, "moduleResolution": "bundler", "allowImportingTsExtensions": true, "resolveJsonModule": true,
    "isolatedModules": true, "noEmit": true, "jsx": "react-jsx", "strict": true, "noUnusedLocals": true,
    "noUnusedParameters": true, "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}`;
const reactMainTsx = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`;
const viteEnvDts = `/// <reference types="vite/client" />`;

// --- VUE PROJECT TEMPLATES ---
const vuePackageJson = `{
  "name": "vue-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": { "dev": "vite", "build": "vue-tsc && vite build", "preview": "vite preview" },
  "dependencies": { "vue": "^3.3.11" },
  "devDependencies": { "@vitejs/plugin-vue": "^4.5.2", "typescript": "^5.2.2", "vite": "^5.0.8", "vue-tsc": "^1.8.25" }
}`;
const vueViteConfig = `import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
export default defineConfig({ plugins: [vue()] });`;
const vueTsConfig = `{
  "compilerOptions": {
    "target": "ES2020", "useDefineForClassFields": true, "module": "ESNext", "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true, "moduleResolution": "bundler", "allowImportingTsExtensions": true, "resolveJsonModule": true,
    "isolatedModules": true, "noEmit": true, "jsx": "preserve", "strict": true, "noUnusedLocals": true,
    "noUnusedParameters": true, "noFallthroughCasesInSwitch": true
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}`;
const vueMainTs = `import { createApp } from 'vue';
import App from './App.vue';
createApp(App).mount('#root');`;


// --- SVELTE PROJECT TEMPLATES ---
const sveltePackageJson = `{
  "name": "svelte-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview", "check": "svelte-check --tsconfig ./tsconfig.json" },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^3.0.1", "@tsconfig/svelte": "^5.0.2", "svelte": "^4.2.8",
    "svelte-check": "^3.6.2", "tslib": "^2.6.2", "typescript": "^5.2.2", "vite": "^5.0.8"
  }
}`;
const svelteViteConfig = `import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
export default defineConfig({ plugins: [svelte()] });`;
const svelteTsConfig = `{
  "extends": "@tsconfig/svelte/tsconfig.json",
  "compilerOptions": { "target": "ESNext", "useDefineForClassFields": true, "module": "ESNext", "resolveJsonModule": true, "allowJs": true, "checkJs": true, "isolatedModules": true },
  "include": ["src/**/*.d.ts", "src/**/*.ts", "src/**/*.js", "src/**/*.svelte"]
}`;
const svelteMainTs = `import App from './App.svelte';
const app = new App({ target: document.getElementById('root')! });
export default app;`;


export async function generateZip(code: string, format: ExportFormat, fileName: string) {
    const zip = new JSZip();
    const safeFileName = fileName.replace(/\s+/g, '-');

    switch (format) {
        case ExportFormat.HTML:
            zip.file('index.html', getHtmlContent(code, fileName));
            break;

        case ExportFormat.REACT:
            zip.file('package.json', reactPackageJson);
            zip.file('vite.config.ts', reactViteConfig);
            zip.file('tsconfig.json', reactTsConfig);
            zip.file('index.html', getBaseIndexHtml(fileName, '/src/main.tsx'));
            zip.file('README.md', readme);
            zip.folder('src')?.file('main.tsx', reactMainTsx)
                               .file('App.tsx', code)
                               .file('vite-env.d.ts', viteEnvDts);
            break;
        
        case ExportFormat.VUE:
            zip.file('package.json', vuePackageJson);
            zip.file('vite.config.ts', vueViteConfig);
            zip.file('tsconfig.json', vueTsConfig);
            zip.file('index.html', getBaseIndexHtml(fileName, '/src/main.ts'));
            zip.file('README.md', readme);
            zip.folder('src')?.file('main.ts', vueMainTs)
                               .file('App.vue', code)
                               .file('vite-env.d.ts', viteEnvDts);
            break;

        case ExportFormat.SVELTE:
            zip.file('package.json', sveltePackageJson);
            zip.file('vite.config.ts', svelteViteConfig);
            zip.file('tsconfig.json', svelteTsConfig);
            zip.file('index.html', getBaseIndexHtml(fileName, '/src/main.ts'));
            zip.file('README.md', readme);
            zip.folder('src')?.file('main.ts', svelteMainTs)
                               .file('App.svelte', code)
                               .file('vite-env.d.ts', viteEnvDts);
            break;
    }

    const zipBlob = await zip.generateAsync({ type: 'blob' });
    saveAs(zipBlob, `${safeFileName}-${format}.zip`);
}